Pro data
rongardF/tvdatafeed pull request #30
Opened 2023-09-26 11:19 UTC by traderjoe1968

Added in ability to download more than 5000 bars of data for TradingView Pro (and above) account holders.

Only the ws URL & headers need to change. See code.

2023-10-21 17:33 UTC, Sinansi commented
I suggest you add this great news to the home page of this package. I always thought it is impossible to download more than 5000 bars until I saw your post here in the pull section. Please, disclose this information on the home page. Thank you!

2023-11-11 10:16 UTC, liebig commented
Thank you for this merge request. Quick question, what exactly is "TradingView Pro (and above)"?  I only know the subscription levels "Basic, Essential, Plus, Premium, Expert, Elite, Ultimate".

2023-11-11 10:26 UTC, Sinansi commented
The Basic subscription is free and it is limited to maximum of 5000 historical bars. So you cannot plot a chart exceeding 5000 price bars. But if you pay more, you get more price bars on your chart.


Historical bars available
Basic: 5K
Essential: 10K
Plus: 10K
Premium: 20K
Expert: 25K
Elite: 30K
Ultimate 40K

Currently tvdatafeed support only the Basic (free) subscription, so with tvdatafeed you cannot download more than 5000 price bars. This merge pull allow those who pay a monthly subscription fee to download more than 5000 price bars.

2023-11-17 08:55 UTC, traderjoe1968 commented
I think it used to be called Pro

Pro = Plus subscription

2024-02-16 21:57 UTC, AssetOverflow commented
so is this now included?

2025-05-11 02:57 UTC, KoushikEng commented
Is not working anymore! Not downloading more than 5000 bars for paid subscriptions. Anyone used it ?

2025-05-11 08:15 UTC, traderjoe1968 commented
The URL is "https://prodata.tradingview.com/" is still valid and login in a non-standard user still works. Spent 1hr investigating.  It is limited to what TV returns ( I managed to get close to 10k data items but not beyond). The issue is in get_hist() around line 269 main.py 
The underlying WebSocket API has changed - Number of Bars no longer works - unless someone is willing to work out the new api  

``` python
# This call seems to be the issue
self.__send_message(
            "create_series",
            [self.chart_session, "s1", "s1", "symbol_1", interval, n_bars],
        )
'''

2025-05-15 01:43 UTC, KoushikEng commented
@traderjoe1968 I have updated the code, working alright now and made a PR on your repo.

2025-05-16 02:43 UTC, KoushikEng approved these changes

2025-07-06 14:41 UTC, KoushikEng requested changes
`pyotp` added two times in **requirements.txt**

2025-07-08 18:04 UTC, KoushikEng approved these changes

2025-12-06 15:54 UTC, tiiiecherle commented
@traderjoe1968 
thanks for your pro branch. Unfortunately the login with your code is no longer working and I hope you can update your code here and on your project site. Thanks

2026-02-16 10:52 UTC, closed without merging